site_name: Osqspeed
site_url: https://indaplus22.github.io/alww-vprytz-project
repo_url: https://github.com/IndaPlus22/alww-vprytz-project/tree/main
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - content.action.edit
    - content.action.view

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: IndaPlus22/alww-vprytz-project
      branch: main
